# Generated by Django 4.1.5 on 2025-03-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_order',
            field=models.BooleanField(default=False),
        ),
    ]
